# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'idea.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(457, 590)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"   }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.apple = QtWidgets.QPushButton(self.centralwidget)
        self.apple.setGeometry(QtCore.QRect(120, 139, 221, 61))
        self.apple.setStyleSheet("QPushButton {\n"
"      background-color: rgb(0, 0, 0); /* Set background color */\n"
"      color: rgb(255, 255, 255); /* Set text color */\n"
"      border-radius: 15px; /* Apply rounded corners */\n"
"      padding-left: 20px; /* Add padding to adjust text position */\n"
"      padding-right: 40px; /* Add padding to move the image to the right */\n"
"     }\n"
"\n"
"     QPushButton::hover {\n"
"      background-color: rgb(91, 91, 91);\n"
"     }")
        self.apple.setObjectName("apple")
        self.google = QtWidgets.QPushButton(self.centralwidget)
        self.google.setGeometry(QtCore.QRect(120, 210, 221, 51))
        self.google.setStyleSheet("QPushButton {\n"
"      background-color: rgb(38, 208, 255); /* Set background color */\n"
"      color: rgb(255, 255, 255); /* Set text color */\n"
"      border-radius: 15px; /* Apply rounded corners */\n"
"      padding-left: 20px; /* Add padding to adjust text position */\n"
"      padding-right: 40px; /* Add padding to move the image to the right */\n"
"     }\n"
"\n"
"     QPushButton::hover {\n"
"      background-color: rgb(30, 169, 255);\n"
"     }")
        self.google.setObjectName("google")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 0, 551, 81))
        self.label.setStyleSheet("font: 16pt \"Segoe UI\";\n"
"     ")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-90, 330, 711, 291))
        self.label_2.setStyleSheet("QLabel {\n"
"      background-image: url(:/newPrefix/water.png);\n"
"     }\n"
"     ")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("watethe.png"))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 300, 201, 31))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"      border-radius: 15px;\n"
"      border: 2px solid rgb(0, 12, 255); /* Blue border */\n"
"     }\n"
"     ")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 340, 201, 31))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"      border-radius: 15px;\n"
"      border: 2px solid rgb(0, 12, 255); /* Blue border */\n"
"     }\n"
"     ")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 306, 61, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 350, 61, 20))
        self.label_4.setObjectName("label_4")
        self.sign = QtWidgets.QPushButton(self.centralwidget)
        self.sign.setGeometry(QtCore.QRect(130, 390, 201, 51))
        self.sign.setStyleSheet("QPushButton {\n"
"      background-color: rgb(38, 208, 255); /* Set background color */\n"
"      color: rgb(255, 255, 255); /* Set text color */\n"
"      border-radius: 15px; /* Apply rounded corners */\n"
"      padding-left: 20px; /* Add padding to adjust text position */\n"
"      padding-right: 40px; /* Add padding to move the image to the right */\n"
"     }\n"
"\n"
"     QPushButton::hover {\n"
"      background-color: rgb(30, 169, 255);\n"
"     }")
        self.sign.setObjectName("sign")
        self.label_2.raise_()
        self.apple.raise_()
        self.google.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.sign.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.apple.setText(_translate("MainWindow", "Continue with Apple"))
        self.google.setText(_translate("MainWindow", "Continue with Google"))
        self.label.setText(_translate("MainWindow", "Welcome To TryDration App"))
        self.label_3.setText(_translate("MainWindow", "Username"))
        self.label_4.setText(_translate("MainWindow", "Password"))
        self.sign.setText(_translate("MainWindow", "Sign Up"))
